# Data Cleaning

In [78]:
import pandas as pd
df = pd.read_csv("customer churn.csv")

## Data Observations Checking
<hr>


**_Numeric Dtypes_**<br>
>- Invalid numeric values
>- Duplicate values on unique field

**_String Dtypes_**
>- Duplicate
>- Typographical Errors
<hr>

### Numeric Datatypes

Use `describe()` to view invalid observations

In [92]:
df.describe()

,Customer_ID,Age,Days_Since_Last_Login,Customer_Service_Calls,Monthly_Spend,Churn
count,10300.000000,9267.000000,10300.000000,10300.000000,9786.000000,10300.000000
mean,14859.237864,33.521852,89.449903,1.787379,300.093737,0.762039
std,2959.197492,11.514686,52.088510,1.363470,4733.134612,0.425856
min,10001.000000,-10.000000,0.000000,-1.000000,-10.000000,0.000000
25%,12275.750000,26.000000,44.000000,1.000000,26.275000,1.000000
50%,14850.500000,33.000000,90.000000,2.000000,66.355000,1.000000
75%,17425.250000,40.000000,135.000000,3.000000,115.915000,1.000000
max,20000.000000,150.000000,179.000000,9.000000,99999.990000,1.000000

**_Findings_**
>---
**_Age:_**<br>
    - have min value of `-10`
    - have a big outlier

**_Customer Service Calls_**<br>
    - have min value of `-1`

**_Monthly_Spend_**<br>
    - have min value of `-10`
    - have a big outlier

<hr>

**_Process_**<br>
>---
Convert all non-positive values in `Age`, `Customer Service Calls`, and `Monthly Spend` into `nan`

In [99]:
df['Age'] = df['Age'].where(df['Age'] > 0 )
df['Customer_Service_Calls'] = df['Customer_Service_Calls'].where(df['Customer_Service_Calls'] > 0 )
df['Monthly_Spend'] = df['Monthly_Spend'].where(df['Monthly_Spend'] > 0 )

for cols in ['Age', 'Customer_Service_Calls', 'Monthly_Spend']:
    print(sorted(df[cols]))

[27.0, 55.0, nan, nan, 22.0, 30.0, 32.0, 43.0, 44.0, 46.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 19.0, 27.0, 34.0, 35.0, 38.0, 38.0, 47.0, 150.0, 150.0, 150.0, 150.0, 150.0, 150.0, 150.0, 150.0, 150.0, 150.0, nan, nan, nan, 14.0, 17.0, 17.0, 21.0, 21.0, 22.0, 23.0, 24.0, 24.0, 25.0, 26.0, 27.0, 28.0, 28.0, 29.0, 29.0, 30.0, 30.0, 30.0, 30.0, 33.0, 33.0, 34.0, 34.0, 34.0, 35.0, 35.0, 35.0, 36.0, 37.0, 37.0, 38.0, 39.0, 41.0, 42.0, 42.0, 44.0, 49.0, nan, 44.0, nan, 21.0, nan, 16.0, 18.0, 18.0, 22.0, 23.0, 23.0, 24.0, 25.0, 25.0, 26.0, 29.0, 29.0, 29.0, 31.0, 31.0, 31.0, 32.0, 32.0, 33.0, 33.0, 34.0, 34.0, 34.0, 34.0, 35.0, 36.0, 37.0, 37.0, 37.0, 38.0, 38.0, 39.0, 39.0, 39.0, 42.0, 44.0, nan, 44.0, nan, 16.0, nan, 11.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 28.0, 32.0, 32.0, 33.0, 34.0, 35.0, 37.0, 39.0, nan, 28.0, 28.0, 36.0, 38.0, 39.0, 39.0, 39.0, 41.0, 42.0, 42.0, 43.0, 45.0, 47.0, 48.0, 50.0, 52.0, nan, nan, nan, nan, nan, nan, 17.0, 21.0, 22.0, 22.0, 24.0, 24.0, 25.0, 38.0, 49.0, nan, 23.0, 26.0, 27.0, 27.0, 30.0, 32.0, 32.0, 32.0, 33.0, 34.0, 34.0, 34.0, 37.0, 37.0, 37.0, 37.0, 38.0, 39.0, 40.0, 40.0, 41.0, 43.0, 44.0, 47.0, 51.0, nan, nan, nan, 53.0, nan, nan, 33.0, nan, 11.0, 15.0, 17.0, 20.0, 20.0, 21.0, 23.0, 23.0, 25.0, 28.0, 29.0, nan, 27.0, 27.0, 27.0, 28.0, 28.0, 29.0, 30.0, 30.0, 32.0, nan, 28.0, 30.0, 33.0, 33.0, 34.0, 34.0, 36.0, 38.0, 41.0, 41.0, 42.0, 46.0, 46.0, 46.0, 46.0, nan, nan, 12.0, 15.0, 17.0, 17.0, 20.0, 22.0, 22.0, 25.0, 29.0, 29.0, 31.0, 34.0, 35.0, 37.0, 38.0, nan, nan, nan, 25.0, 25.0, 25.0, 28.0, 31.0, 36.0, nan, 31.0, 36.0, 39.0, 40.0, 40.0, 40.0, 41.0, 43.0, nan, nan, 37.0, 53.0, nan, 44.0, nan, nan, 20.0, 23.0, 24.0, 24.0, 26.0, 26.0, 27.0, 27.0, 27.0, 28.0, 31.0, 31.0, 31.0, 32.0, 34.0, 36.0, 36.0, 36.0, 37.0, 38.0, 39.0, 39.0, 39.0, 39.0, 39.0, 40.0, 40.0, 40.0, 40.0, 41.0, 42.0, 45.0, 45.0, 45.0, 45.0, 45.0, 48.0, 51.0, 52.0, 52.0, nan, 12.0, 25.0, 36.0, 37.0, nan, nan, 14.0, 16.0, 22.0, 22.0, 24.0, 26.0, 30.0, 31.0, 31.0, 31.0, 32.0, 32.0, 34.0, 34.0, 34.0, 35.0, 35.0, 36.0, 36.0, 36.0, 38.0, 38.0, 40.0, nan, 41.0, 47.0, nan, nan, nan, nan, 35.0, 43.0, nan, nan, 11.0, 12.0, 12.0, 16.0, 18.0, 19.0, 22.0, 22.0, 24.0, 24.0, 25.0, 27.0, 28.0, 29.0, 29.0, 30.0, 31.0, 33.0, 33.0, 33.0, 34.0, 34.0, 36.0, 36.0, 36.0, 38.0, 38.0, 39.0, 39.0, 40.0, 43.0, 45.0, 45.0, 48.0, 48.0, 49.0, 49.0, 50.0, 59.0, nan, nan, 16.0, 16.0, 20.0, 22.0, 22.0, 24.0, 30.0, 31.0, 31.0, 31.0, 31.0, 32.0, 32.0, 33.0, 34.0, 34.0, 35.0, 36.0, 36.0, 37.0, 37.0, 38.0, 39.0, 48.0, nan, 39.0, nan, nan, 39.0, 41.0, 43.0, 45.0, nan, 41.0, 47.0, 48.0, 49.0, nan, 42.0, nan, 19.0, 23.0, 28.0, 28.0, 28.0, 28.0, 29.0, 31.0, 31.0, 31.0, 32.0, 32.0, 32.0, 33.0, 33.0, 33.0, 35.0, 35.0, 35.0, 36.0, 37.0, 38.0, 39.0, 39.0, 39.0, 40.0, 40.0, 41.0, 41.0, 41.0, 42.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 49.0, 50.0, nan, 46.0, nan, nan, 32.0, 50.0, nan, 16.0, 17.0, 19.0, 22.0, 23.0, 25.0, 25.0, 25.0, 26.0, 26.0, 27.0, 29.0, 30.0, 30.0, 30.0, 31.0, 31.0, 31.0, 33.0, 35.0, 35.0, 36.0, 36.0, 37.0, 39.0, 39.0, 41.0, 43.0, 43.0, 43.0, 44.0, 44.0, 48.0, 50.0, nan, nan, nan, nan, 14.0, 18.0, 19.0, 19.0, 19.0, 21.0, 21.0, 21.0, 23.0, 23.0, 25.0, 27.0, 27.0, 28.0, 29.0, 33.0, 33.0, 34.0, 34.0, 34.0, 35.0, 35.0, 36.0, 37.0, 37.0, 39.0, 39.0, 40.0, 43.0, nan, nan, 39.0, 52.0, nan, nan, 36.0, 40.0, 48.0, nan, nan, nan, 14.0, 18.0, 18.0, 19.0, 19.0, 20.0, 22.0, 23.0, 24.0, 24.0, 25.0, 26.0, 27.0, 28.0, 28.0, 30.0, 30.0, 31.0, 32.0, 33.0, 33.0, 34.0, 35.0, 35.0, 38.0, 38.0, 39.0, 39.0, 39.0, 39.0, 39.0, 40.0, 40.0, 42.0, 44.0, 44.0, nan, 40.0, 55.0, 58.0, nan, 20.0, 22.0, 25.0, 29.0, 34.0, nan, nan, 9.0, 18.0, 23.0, 23.0, 26.0, 27.0, 27.0, 29.0, 29.0, 30.0, 32.0, 32.0, 32.0, 32.0, 35.0, 36.0, 36.0, 37.0, 37.0, 37.0, 38.0, 39.0, 39.0, 39.0, 39.0, 40.0, 41.0, 43.0, 43.0, 43.0, 49.0, 49.0, nan, 14.0, 15.0, 17.0, 18.0, 18.0, 19.0, 22.0, 24.0, 24.0, 25.0, 27.0, 27.0, 28.0, 29.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 34.0, 35.0, 35.0, 36.0, 36.0, 36.0, 37.0, 38.0, 39.0, 39.0, 40.0, 41.0, 42.0, 42.0, 45.0, 45.0, 46.0, 49.0, 49.0, 57.0, nan, 8.0, nan, 12.0, 24.0, 24.0, 25.0, 25.0, 25.0, 26.0, 27.0, 27.0, 30.0, 32.0, 33.0, 34.0, 34.0, 34.0, 35.0, 35.0, 37.0, 39.0, 40.0, 41.0, 42.0, 45.0, nan, nan, nan, 39.0, 40.0, 40.0, 41.0, 43.0, 46.0, 49.0, nan, 49.0, nan, nan, 9.0, 13.0, 16.0, 21.0, 22.0, 22.0, 23.0, 26.0, 27.0, 28.0, 29.0, 30.0, 30.0, 30.0, 31.0, 32.0, 32.0, 32.0, 32.0, 34.0, 34.0, 35.0, 37.0, 40.0, 40.0, nan, nan, 36.0, 39.0, 40.0, 41.0, 42.0, 43.0, nan, nan, 42.0, 43.0, 45.0, 46.0, nan, nan, 34.0, nan, 13.0, 15.0, 16.0, 19.0, 20.0, 23.0, 26.0, 29.0, 29.0, 30.0, 30.0, 31.0, 32.0, 32.0, 32.0, 34.0, 34.0, 35.0, 35.0, 35.0, 38.0, 38.0, 39.0, 39.0, 40.0, 40.0, 40.0, 41.0, 41.0, 41.0, 42.0, 44.0, 45.0, 48.0, 48.0, nan, nan, nan, 46.0, 51.0, nan, 14.0, 16.0, 17.0, 17.0, 18.0, 18.0, 20.0, 22.0, 23.0, 23.0, 28.0, nan, 22.0, 26.0, 27.0, 27.0, 27.0, 30.0, 32.0, 33.0, 34.0, 35.0, 35.0, 35.0, 35.0, 36.0, 38.0, 44.0, 47.0, nan, 36.0, 36.0, 38.0, 39.0, 42.0, 47.0, 53.0, nan, 52.0, nan, nan, 16.0, 26.0, 26.0, 27.0, 28.0, 30.0, 31.0, 32.0, 32.0, 33.0, 33.0, 33.0, 33.0, 34.0, 34.0, 35.0, 35.0, 35.0, 36.0, 36.0, 37.0, 38.0, 38.0, 38.0, 39.0, 40.0, 41.0, 41.0, 42.0, 43.0, 43.0, 44.0, 45.0, 46.0, nan, nan, 43.0, 45.0, 49.0, nan, nan, 53.0, nan, 16.0, 19.0, 20.0, 28.0, 30.0, 31.0, 31.0, 33.0, 35.0, nan, 34.0, nan, nan, 21.0, 33.0, 33.0, 34.0, 37.0, 37.0, 38.0, 38.0, 38.0, 39.0, 39.0, 40.0, 41.0, 43.0, 43.0, 44.0, 46.0, 48.0, 48.0, 51.0, 54.0, nan, nan, nan, nan, 16.0, 18.0, 19.0, 19.0, 20.0, 20.0, 21.0, 22.0, 22.0, 23.0, 25.0, 25.0, 25.0, 26.0, 26.0, 28.0, 30.0, 30.0, 30.0, 32.0, 32.0, 32.0, 32.0, 34.0, 36.0, 36.0, 36.0, 37.0, 37.0, 38.0, 40.0, 43.0, 45.0, nan, nan, nan, 40.0, 42.0, 45.0, 46.0, 50.0, nan, 4.0, 15.0, 19.0, 19.0, 20.0, 23.0, 25.0, 25.0, 26.0, 27.0, 27.0, 28.0, 29.0, 30.0, 30.0, 30.0, 31.0, 31.0, 31.0, 34.0, 37.0, 38.0, 39.0, nan, 34.0, 35.0, 36.0, 38.0, 38.0, 38.0, 40.0, 40.0, 42.0, 43.0, 44.0, 45.0, 46.0, 51.0, nan, nan, nan, 15.0, 16.0, 18.0, 18.0, 18.0, 21.0, 22.0, 22.0, 22.0, 24.0, 24.0, 25.0, 27.0, 27.0, 27.0, 30.0, 31.0, 31.0, 32.0, 32.0, 32.0, 32.0, 32.0, 35.0, 35.0, 36.0, 36.0, 38.0, 38.0, 40.0, 41.0, 41.0, 45.0, 46.0, 58.0, nan, 47.0, nan, 44.0, nan, nan, 22.0, 23.0, 23.0, 24.0, 25.0, 25.0, 26.0, 28.0, 29.0, 30.0, 32.0, 33.0, 33.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 34.0, 35.0, 35.0, 35.0, 36.0, 37.0, 37.0, 38.0, 38.0, 40.0, 40.0, 41.0, 42.0, 43.0, 43.0, 43.0, 44.0, nan, nan, 45.0, nan, 9.0, 17.0, 18.0, 19.0, 20.0, 20.0, 21.0, 23.0, 25.0, 25.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 32.0, 33.0, 33.0, 33.0, 33.0, 33.0, 34.0, 34.0, 35.0, 36.0, 36.0, 40.0, 40.0, 40.0, 43.0, 43.0, 43.0, 46.0, 47.0, nan, nan, nan, nan, nan, 14.0, 17.0, 20.0, 22.0, 23.0, 23.0, 23.0, 25.0, 26.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 33.0, 33.0, 34.0, 34.0, 35.0, 35.0, 35.0, 36.0, 36.0, 39.0, 39.0, 40.0, 40.0, 42.0, 43.0, 45.0, nan, 36.0, 43.0, 43.0, 43.0, 43.0, 47.0, 47.0, 49.0, 50.0, nan, 13.0, 13.0, 17.0, 18.0, 21.0, 22.0, 23.0, 25.0, 26.0, 27.0, 28.0, 29.0, 29.0, 29.0, 30.0, 30.0, 30.0, 31.0, 31.0, 32.0, 33.0, 33.0, 35.0, 36.0, 37.0, 37.0, 38.0, 39.0, 41.0, 42.0, 43.0, 43.0, 44.0, 46.0, 48.0, 50.0, 58.0, nan, 58.0, nan, nan, 10.0, 19.0, 21.0, 26.0, 26.0, 28.0, 29.0, 30.0, 30.0, 31.0, 31.0, 32.0, 33.0, 33.0, 33.0, 34.0, 35.0, 35.0, 36.0, 36.0, 36.0, 36.0, 38.0, 40.0, nan, nan, 36.0, 38.0, 38.0, 39.0, 40.0, 41.0, 45.0, 47.0, nan, 44.0, 47.0, 48.0, nan, 51.0, 62.0, nan, 16.0, 16.0, 19.0, 19.0, 21.0, 22.0, 22.0, 24.0, 24.0, 25.0, 26.0, 27.0, 27.0, 28.0, 30.0, 30.0, 30.0, 31.0, 31.0, 32.0, 32.0, 33.0, 35.0, 47.0, nan, nan, nan, 39.0, 40.0, 40.0, nan, 37.0, 40.0, 40.0, 45.0, 47.0, 51.0, 51.0, 51.0, nan, nan, 16.0, 18.0, 19.0, 19.0, 20.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 27.0, 28.0, 29.0, 30.0, 30.0, 30.0, 31.0, 32.0, 32.0, 32.0, 33.0, 33.0, 33.0, 34.0, 34.0, 35.0, 37.0, 38.0, 38.0, 40.0, 41.0, 43.0, nan, 41.0, 41.0, 43.0, 46.0, nan, nan, nan, 21.0, 22.0, 23.0, 23.0, 23.0, 26.0, 26.0, 27.0, 27.0, 28.0, 30.0, 30.0, 30.0, 30.0, 31.0, 31.0, 31.0, 32.0, 33.0, 33.0, 34.0, 36.0, 37.0, 37.0, 37.0, 38.0, 38.0, 38.0, 38.0, 38.0, 40.0, 41.0, 42.0, 42.0, 46.0, 50.0, 51.0, 52.0, nan, nan, nan, 5.0, 16.0, 16.0, 22.0, 23.0, 24.0, 25.0, 25.0, 28.0, 28.0, 28.0, 31.0, 31.0, 32.0, 33.0, 35.0, 35.0, 36.0, 36.0, 37.0, 37.0, 38.0, 38.0, 39.0, 39.0, 43.0, 43.0, 44.0, nan, 54.0, nan, nan, 39.0, 39.0, 41.0, 44.0, 44.0, 51.0, nan, 58.0, nan, 34.0, nan, 14.0, 16.0, 22.0, 23.0, 23.0, 24.0, 25.0, 26.0, 26.0, 27.0, 28.0, 28.0, 28.0, 28.0, 32.0, 33.0, 33.0, 34.0, 34.0, 34.0, 43.0, 47.0, nan, nan, 34.0, 36.0, 37.0, 41.0, 41.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 50.0, 53.0, nan, nan, 8.0, 10.0, 11.0, 21.0, 23.0, 24.0, 24.0, 28.0, 28.0, 28.0, 29.0, 29.0, 29.0, 29.0, 30.0, 30.0, 31.0, 32.0, 32.0, 33.0, 33.0, 33.0, 33.0, 34.0, 35.0, 35.0, 36.0, 36.0, 36.0, 37.0, 39.0, 40.0, 40.0, 41.0, 41.0, 41.0, 43.0, 47.0, nan, nan, nan, 14.0, 15.0, 19.0, 23.0, 25.0, 26.0, 28.0, 28.0, 28.0, 32.0, nan, 34.0, nan, 18.0, 28.0, 29.0, 30.0, 31.0, 31.0, 32.0, 33.0, 35.0, 35.0, 35.0, 36.0, 36.0, 36.0, 37.0, 39.0, 40.0, 40.0, 42.0, 45.0, 47.0, 48.0, 48.0, 50.0, 54.0, nan, nan, 11.0, 13.0, 19.0, 24.0, 24.0, 24.0, 26.0, 27.0, 27.0, 28.0, 29.0, 30.0, 30.0, 31.0, 32.0, 32.0, 33.0, 35.0, 35.0, 37.0, 37.0, 38.0, 38.0, 38.0, 39.0, 40.0, 40.0, 42.0, 42.0, 43.0, 44.0, 44.0, 48.0, 50.0, nan, nan, 45.0, 45.0, 50.0, 51.0, nan, nan, 15.0, 19.0, 20.0, 21.0, 21.0, 21.0, 25.0, 27.0, 28.0, 29.0, 30.0, 31.0, 31.0, 33.0, 34.0, 36.0, 38.0, 39.0, 52.0, nan, nan, 41.0, 42.0, nan, 23.0, 24.0, 25.0, 30.0, 30.0, 32.0, 32.0, 34.0, 34.0, 34.0, 42.0, 42.0, 46.0, 51.0, nan, nan, nan, 15.0, 16.0, 18.0, 18.0, 21.0, 23.0, 23.0, 24.0, 24.0, 26.0, 28.0, 28.0, 29.0, 30.0, 31.0, 32.0, 32.0, 32.0, 33.0, 33.0, 34.0, 35.0, 35.0, 36.0, 36.0, 38.0, 38.0, 39.0, 40.0, 43.0, 46.0, 48.0, 48.0, nan, 52.0, 55.0, nan, nan, nan, nan, nan, 8.0, 19.0, 21.0, 22.0, 24.0, 25.0, 32.0, nan, 26.0, 27.0, 27.0, 28.0, 29.0, 29.0, 29.0, 29.0, 31.0, 32.0, 33.0, 33.0, 33.0, 34.0, 34.0, 36.0, 36.0, 38.0, 38.0, 39.0, 40.0, 40.0, 41.0, 42.0, 43.0, 43.0, nan, nan, 40.0, nan, 44.0, 49.0, 55.0, 57.0, nan, 3.0, 16.0, 18.0, 23.0, 23.0, 23.0, 24.0, 26.0, 26.0, 28.0, 28.0, 29.0, 31.0, 32.0, 32.0, 32.0, 33.0, 34.0, 36.0, 38.0, 39.0, 44.0, 46.0, nan, nan, 36.0, 36.0, 36.0, 39.0, 39.0, 40.0, 41.0, 42.0, 43.0, 43.0, 46.0, 56.0, nan, nan, 15.0, 17.0, 17.0, 17.0, 18.0, 19.0, 19.0, 21.0, 23.0, 23.0, 24.0, 24.0, 25.0, 25.0, 26.0, 26.0, 26.0, 27.0, 27.0, 27.0, 30.0, 30.0, 31.0, 31.0, 31.0, 32.0, 32.0, 32.0, 32.0, 32.0, 33.0, 34.0, 34.0, 35.0, 35.0, 35.0, 35.0, 36.0, 36.0, 36.0, 36.0, 37.0, 37.0, 37.0, 37.0, 37.0, 38.0, 38.0, 39.0, 39.0, 40.0, 40.0, 40.0, 42.0, 43.0, 43.0, 45.0, 45.0, 47.0, 49.0, 53.0, 53.0, 54.0, nan, 25.0, 28.0, nan, 40.0, 43.0, 43.0, 47.0, 49.0, 51.0, 54.0, nan, 51.0, 58.0, nan, nan, 20.0, 20.0, 22.0, 23.0, 23.0, 24.0, 27.0, 27.0, 28.0, 28.0, 29.0, 30.0, 30.0, 30.0, 31.0, 32.0, 33.0, 33.0, 34.0, 34.0, 36.0, 36.0, 38.0, 38.0, 39.0, 40.0, 41.0, 42.0, 45.0, 48.0, 54.0, nan, 48.0, nan, 46.0, nan, 58.0, nan, nan, nan, 47.0, 50.0, 60.0, nan, 9.0, 18.0, 21.0, 22.0, 24.0, 28.0, 29.0, 29.0, 29.0, 30.0, 31.0, 31.0, 32.0, 34.0, 34.0, 37.0, 37.0, 37.0, 38.0, 39.0, 39.0, 43.0, 44.0, 48.0, 50.0, 52.0, nan, nan, 39.0, 39.0, 42.0, 50.0, 53.0, nan, nan, nan, 12.0, 14.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 22.0, 22.0, 22.0, 22.0, 23.0, 23.0, 23.0, 23.0, 24.0, 24.0, 24.0, 24.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 26.0, 26.0, 26.0, 26.0, 27.0, 27.0, 27.0, 27.0, 28.0, 28.0, 28.0, 29.0, 29.0, 29.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 31.0, 31.0, 31.0, 32.0, 32.0, 32.0, 32.0, 32.0, 32.0, 32.0, 32.0, 32.0, 33.0, 33.0, 33.0, 33.0, 34.0, 34.0, 35.0, 35.0, 35.0, 35.0, 36.0, 36.0, 36.0, 37.0, 37.0, 38.0, 38.0, 38.0, 39.0, 39.0, 42.0, 45.0, 45.0, 45.0, nan, 39.0, 46.0, 47.0, 52.0, 66.0, nan, 31.0, 33.0, 35.0, 35.0, 35.0, 36.0, 36.0, 37.0, 39.0, 39.0, 41.0, 41.0, 42.0, 45.0, 48.0, 48.0, 54.0, nan, 52.0, nan, 51.0, 59.0, nan, 19.0, 19.0, 20.0, 21.0, 21.0, 21.0, 22.0, 23.0, 24.0, 24.0, 24.0, 25.0, 27.0, 27.0, 28.0, 28.0, 28.0, 28.0, 29.0, 32.0, 32.0, 32.0, 33.0, 33.0, 34.0, 34.0, 35.0, 36.0, 36.0, 38.0, 38.0, 38.0, 47.0, 52.0, nan, 46.0, 47.0, 52.0, nan, 57.0, nan, 15.0, 22.0, 22.0, 24.0, 25.0, 27.0, 28.0, 29.0, 31.0, 31.0, 32.0, 32.0, 34.0, 36.0, 45.0, nan, 19.0, 21.0, 33.0, 34.0, 34.0, 35.0, 36.0, 36.0, 36.0, 36.0, 38.0, 38.0, 38.0, 39.0, 39.0, 41.0, 42.0, 46.0, 48.0, nan, 48.0, 53.0, nan, nan, 3.0, 20.0, 20.0, 21.0, 21.0, 22.0, 24.0, 27.0, 27.0, 28.0, 28.0, 28.0, 28.0, 30.0, 30.0, 31.0, 32.0, 32.0, 34.0, 35.0, 37.0, 38.0, 39.0, 39.0, 41.0, 41.0, 41.0, 41.0, 41.0, 42.0, 43.0, 43.0, 45.0, 50.0, 58.0, nan, 51.0, nan, nan, 45.0, nan, 20.0, nan, 14.0, 14.0, 18.0, 19.0, 20.0, 21.0, 21.0, 22.0, 22.0, 25.0, 25.0, 26.0, 27.0, 28.0, 28.0, 28.0, 29.0, 30.0, 32.0, 32.0, 32.0, 35.0, 36.0, 36.0, 38.0, 38.0, 40.0, 40.0, 41.0, 48.0, 49.0, 49.0, 53.0, nan, nan, 63.0, nan, 49.0, nan, 23.0, nan, 14.0, 20.0, 21.0, 22.0, 22.0, 28.0, 28.0, 28.0, 31.0, 33.0, 34.0, 35.0, 35.0, 35.0, 35.0, 35.0, 36.0, 36.0, 36.0, 36.0, 37.0, 37.0, 38.0, 38.0, 39.0, 40.0, 41.0, 41.0, 41.0, 44.0, 44.0, 47.0, 48.0, nan, nan, 48.0, 48.0, 55.0, nan, 18.0, 19.0, 19.0, 22.0, 23.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 57.0, nan, 28.0, 34.0, 34.0, 34.0, 34.0, 35.0, 37.0, 38.0, nan, 11.0, 24.0, 34.0, 37.0, 44.0, nan, 42.0, 43.0, nan, nan, 39.0, 42.0, 43.0, 46.0, 47.0, 47.0, 48.0, 52.0, 53.0, 56.0, nan, 36.0, 37.0, 37.0, 38.0, nan, 19.0, 22.0, 35.0, 36.0, 37.0, 37.0, 38.0, 38.0, 39.0, 40.0, 40.0, 40.0, 41.0, 41.0, 41.0, 42.0, 42.0, 43.0, 43.0, 44.0, 45.0, 46.0, 46.0, 47.0, 47.0, 52.0, nan, 47.0, nan, nan, 17.0, 21.0, 22.0, 22.0, 23.0, 25.0, 26.0, 26.0, 28.0, 30.0, 30.0, 31.0, 32.0, 32.0, 32.0, 34.0, 34.0, 34.0, 34.0, 35.0, 35.0, 36.0, 39.0, 39.0, 39.0, 39.0, 39.0, 40.0, 40.0, 42.0, 43.0, 44.0, 44.0, 46.0, 46.0, 46.0, 49.0, 49.0, 49.0, 52.0, 54.0, nan, 48.0, nan, 45.0, 48.0, 50.0, 59.0, 59.0, 60.0, nan, nan, nan, 13.0, 14.0, 19.0, 20.0, 20.0, 20.0, 21.0, 21.0, 23.0, 24.0, 24.0, 25.0, 26.0, 27.0, 30.0, 30.0, 31.0, 31.0, 33.0, 33.0, 34.0, 35.0, 40.0, nan, 36.0, 36.0, 38.0, 39.0, 40.0, 40.0, 41.0, 44.0, nan, 41.0, 42.0, 45.0, 45.0, 49.0, 51.0, 55.0, nan, 35.0, nan, 10.0, 10.0, 14.0, 14.0, 17.0, 20.0, 21.0, 23.0, 24.0, 25.0, 25.0, 26.0, 27.0, 27.0, 29.0, 29.0, 29.0, 30.0, 31.0, 31.0, 33.0, 34.0, 35.0, 36.0, 37.0, 40.0, 41.0, 42.0, 43.0, 44.0, 46.0, nan, 44.0, 47.0, 47.0, 52.0, nan, nan, 15.0, 19.0, 21.0, 22.0, 23.0, 23.0, 24.0, 24.0, 24.0, 24.0, 25.0, 26.0, 29.0, 31.0, 32.0, 33.0, 33.0, 34.0, 35.0, 35.0, 35.0, 35.0, 35.0, 35.0, 35.0, 36.0, 37.0, 38.0, 38.0, 41.0, 42.0, 42.0, 44.0, 47.0, 50.0, 58.0, nan, 47.0, nan, 10.0, 15.0, 16.0, 18.0, 19.0, 20.0, 21.0, 26.0, 26.0, 27.0, 27.0, 28.0, 29.0, 29.0, 30.0, 30.0, 31.0, 31.0, 31.0, 32.0, 32.0, 33.0, 35.0, 35.0, 36.0, 36.0, 37.0, 37.0, 37.0, 39.0, 39.0, 39.0, 40.0, 41.0, 46.0, 48.0, nan, nan, 45.0, 50.0, nan, 13.0, 16.0, 21.0, 22.0, 25.0, 25.0, 26.0, 27.0, 27.0, 28.0, 28.0, 28.0, 28.0, 29.0, 29.0, 30.0, 31.0, 31.0, 31.0, 32.0, 34.0, 34.0, 34.0, 34.0, 36.0, 36.0, 37.0, 39.0, 39.0, 39.0, 40.0, 41.0, 41.0, 42.0, 42.0, 44.0, 44.0, 44.0, 45.0, 45.0, 46.0, 48.0, 49.0, 51.0, 51.0, 51.0, 51.0, 52.0, nan, 5.0, 16.0, 16.0, 16.0, 18.0, 18.0, 19.0, 20.0, 20.0, 21.0, 21.0, 21.0, 21.0, 22.0, 23.0, 23.0, 24.0, 24.0, 24.0, 25.0, 25.0, 25.0, 26.0, 27.0, 28.0, 28.0, 29.0, 29.0, 29.0, 29.0, 30.0, 30.0, 31.0, 32.0, 32.0, 33.0, 33.0, 33.0, 33.0, 34.0, 34.0, 34.0, 34.0, 35.0, 35.0, 35.0, 35.0, 35.0, 35.0, 36.0, 36.0, 37.0, 37.0, 38.0, 38.0, 39.0, 39.0, 40.0, 40.0, 40.0, 40.0, 41.0, 41.0, 42.0, 42.0, 42.0, 44.0, 53.0, 63.0, nan, nan, nan, nan, 49.0, nan, 33.0, 35.0, nan, 15.0, 17.0, 19.0, 22.0, 22.0, 24.0, 25.0, 26.0, 28.0, 28.0, 28.0, 31.0, 32.0, 33.0, 36.0, 37.0, 38.0, 40.0, 41.0, 56.0, nan, nan, 19.0, 37.0, 38.0, 41.0, 42.0, 43.0, 45.0, nan, 40.0, 44.0, 45.0, 48.0, 49.0, 50.0, nan, 10.0, 10.0, 11.0, 18.0, 18.0, 20.0, 21.0, 21.0, 22.0, 23.0, 25.0, 26.0, 26.0, 26.0, 26.0, 27.0, 27.0, 27.0, 29.0, 29.0, 30.0, 32.0, 32.0, 33.0, 34.0, 37.0, 39.0, 39.0, 40.0, 40.0, 40.0, 42.0, 42.0, 43.0, 50.0, nan, nan, 44.0, 45.0, nan, 10.0, 13.0, 19.0, 21.0, 22.0, 23.0, 25.0, 26.0, 26.0, 26.0, 27.0, 29.0, 30.0, 31.0, 31.0, 32.0, 33.0, 33.0, 33.0, 33.0, 35.0, 36.0, 36.0, 37.0, 39.0, 39.0, 40.0, 41.0, 42.0, 42.0, 44.0, 46.0, 49.0, 51.0, 52.0, 52.0, 53.0, nan, nan, nan, nan, nan, nan, 17.0, 19.0, 22.0, 22.0, 22.0, 22.0, 25.0, 26.0, 26.0, 28.0, 28.0, 29.0, 32.0, 32.0, 32.0, 32.0, 32.0, 33.0, 35.0, 35.0, 35.0, 37.0, 39.0, 40.0, 41.0, 41.0, 41.0, 42.0, 42.0, 43.0, 43.0, 49.0, 50.0, 50.0, 51.0, nan, 51.0, 56.0, nan, nan, nan, 18.0, 20.0, 20.0, 21.0, 21.0, 23.0, 24.0, 26.0, 27.0, 27.0, 28.0, 28.0, 29.0, 30.0, 31.0, 32.0, 32.0, 32.0, 33.0, 33.0, 35.0, 35.0, 36.0, 36.0, 38.0, 38.0, 39.0, 39.0, 39.0, 39.0, 39.0, 41.0, 41.0, 42.0, 42.0, 45.0, 50.0, 51.0, 53.0, nan, nan, 17.0, 18.0, 21.0, 21.0, 26.0, 26.0, 29.0, 42.0, nan, 22.0, 27.0, 28.0, 29.0, 30.0, 30.0, 30.0, 34.0, 35.0, 36.0, 36.0, 37.0, 38.0, 39.0, 39.0, 39.0, 39.0, 39.0, 40.0, 41.0, 42.0, 42.0, 44.0, 44.0, 45.0, 50.0, 61.0, nan, nan, nan, 7.0, 15.0, 17.0, 18.0, 19.0, 20.0, 22.0, 22.0, 22.0, 27.0, 29.0, 29.0, 31.0, 32.0, 33.0, 34.0, 36.0, 36.0, 36.0, 38.0, 38.0, 38.0, 38.0, 38.0, 39.0, 40.0, 40.0, 40.0, 44.0, 46.0, 46.0, 46.0, 47.0, 48.0, 49.0, 49.0, 50.0, 51.0, 55.0, nan, nan, nan, 63.0, nan, 43.0, 46.0, 51.0, nan, nan, nan, 17.0, 19.0, 21.0, 21.0, 22.0, 22.0, 24.0, 25.0, 28.0, 28.0, 28.0, 29.0, 31.0, 32.0, 32.0, 33.0, 33.0, 33.0, 34.0, 34.0, 35.0, 35.0, 36.0, 36.0, 39.0, 39.0, 40.0, 40.0, 40.0, 40.0, 42.0, 42.0, 42.0, 43.0, 43.0, 44.0, 44.0, 46.0, 46.0, 62.0, nan, nan, 6.0, nan, 9.0, 20.0, 21.0, 21.0, 23.0, 24.0, 24.0, 26.0, 28.0, 28.0, 31.0, 31.0, 31.0, 32.0, 32.0, 32.0, 33.0, 33.0, 33.0, 33.0, 35.0, 36.0, 37.0, 38.0, 39.0, 39.0, 39.0, 39.0, 41.0, 41.0, 41.0, 42.0, 47.0, nan, 43.0, nan, 45.0, 56.0, nan, 12.0, 16.0, 19.0, 21.0, 22.0, 23.0, 25.0, 25.0, 25.0, 26.0, 27.0, 28.0, 28.0, 28.0, 29.0, 29.0, 32.0, 32.0, 33.0, 34.0, 35.0, 35.0, 35.0, 35.0, 36.0, 37.0, 39.0, 40.0, nan, 40.0, 40.0, 41.0, 45.0, 46.0, 46.0, 49.0, 49.0, 50.0, 51.0, 51.0, nan, 51.0, nan, 12.0, 14.0, 19.0, 20.0, 21.0, 21.0, 25.0, 26.0, 27.0, 30.0, 30.0, 31.0, 31.0, 32.0, 33.0, 34.0, 34.0, 34.0, 35.0, 36.0, 37.0, 38.0, 38.0, 39.0, 40.0, 41.0, 41.0, 42.0, 47.0, 48.0, nan, nan, 43.0, 48.0, 48.0, 51.0, nan, 50.0, nan, nan, nan, 9.0, 16.0, 17.0, 18.0, 18.0, 22.0, 23.0, 26.0, 26.0, 27.0, 28.0, 29.0, 31.0, 31.0, 31.0, 31.0, 32.0, 32.0, 33.0, 33.0, 34.0, 34.0, 37.0, 38.0, 38.0, 38.0, 38.0, 39.0, 39.0, 39.0, 40.0, 41.0, 45.0, 46.0, 56.0, nan, nan, 40.0, 47.0, nan, 17.0, 18.0, 18.0, 23.0, 24.0, 24.0, 25.0, 25.0, 26.0, 26.0, 26.0, 28.0, 28.0, 28.0, 29.0, 30.0, 31.0, 31.0, 32.0, 32.0, 33.0, 34.0, 34.0, 34.0, 35.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 41.0, 41.0, 42.0, 46.0, 47.0, 48.0, nan, nan, nan, 12.0, nan, 10.0, 10.0, 17.0, 18.0, 19.0, 19.0, 21.0, 23.0, 24.0, 24.0, 25.0, 28.0, 30.0, 32.0, 32.0, 33.0, 34.0, 36.0, 36.0, 38.0, 40.0, 41.0, 42.0, 42.0, 42.0, 43.0, nan, 42.0, 43.0, 45.0, 48.0, 48.0, nan, nan, 45.0, 47.0, 49.0, 52.0, 55.0, nan, 6.0, 8.0, 14.0, 14.0, 16.0, 17.0, 17.0, 18.0, 18.0, 18.0, 19.0, 19.0, 21.0, 21.0, 21.0, 22.0, 22.0, 22.0, 23.0, 23.0, 23.0, 24.0, 24.0, 24.0, 24.0, 24.0, 24.0, 25.0, 25.0, 25.0, 25.0, 26.0, 26.0, 26.0, 26.0, 26.0, 27.0, 27.0, 28.0, 28.0, 28.0, 29.0, 29.0, 29.0, 29.0, 29.0, 29.0, 30.0, 30.0, 30.0, 31.0, 32.0, 33.0, 33.0, 33.0, 33.0, 33.0, 33.0, 34.0, 34.0, 34.0, 35.0, 36.0, 36.0, 37.0, 37.0, 38.0, 40.0, 40.0, 41.0, 42.0, 42.0, 43.0, 44.0, 45.0, 46.0, nan, 53.0, nan, nan, 11.0, 14.0, 15.0, 15.0, 19.0, 23.0, 24.0, 26.0, 27.0, 27.0, 28.0, 28.0, 30.0, 31.0, 31.0, 32.0, 32.0, 34.0, 34.0, 35.0, 37.0, 37.0, 37.0, 38.0, 40.0, 40.0, 41.0, 41.0, 42.0, 43.0, 43.0, 44.0, 44.0, 45.0, 45.0, 47.0, 47.0, 50.0, 51.0, 52.0, 56.0, nan, 16.0, 17.0, 20.0, 21.0, 23.0, 23.0, 24.0, 25.0, 25.0, 25.0, 26.0, 28.0, 30.0, 30.0, 30.0, 30.0, 31.0, 31.0, 31.0, 31.0, 32.0, 35.0, 36.0, 43.0, nan, 35.0, 35.0, 35.0, 

In [140]:
inv_age = df[df['Age'] > 70]
inv_age

,Customer_ID,Gender,Region,Subscription_Plan,Payment_Method,Age,Days_Since_Last_Login,Customer_Service_Calls,Monthly_Spend,Churn
21,10022,Male,South,Plus,PayPal,150.0,150,2.0,191.92,1
22,10023,Male,West,Basic,Crypto,150.0,116,NaN,108.58,0
23,10024,Male,North,Pro,PayPal,150.0,174,2.0,122.11,1
24,10025,Female,West,Basic,Credit Card,150.0,86,4.0,71.26,0
25,10026,Female,South,Plus,E-Wallet,150.0,73,1.0,167.01,1
26,10027,Male,East,Basic,Credit Card,150.0,65,NaN,NaN,1
27,10028,Female,South,Pro,E-Wallet,150.0,36,1.0,73.77,0
28,10029,Female,East,Basic,Credit Card,150.0,124,2.0,72.01,1
29,10030,Male,East,Basic,Credit Card,150.0,165,4.0,22.69,1
30,10031,Female,East,Pro,Crypto,150.0,0,3.0,92.74,1
10021,10022,Male,South,Plus,PayPal,150.0,150,2.0,191.92,1
10022,10023,Male,West,Basic,Crypto,150.0,116,NaN,108.58,0
10023,10024,Male,North,Pro,PayPal,150.0,174,2.0,122.11,1
10024,10025,Female,West,Basic,Credit Card,150.0,86,4.0,71.26,0
10025,10026,Female,South,Plus,E-Wallet,150.0,73,1.0,167.01,1
10026,10027,Male,East,Basic,Credit Card,150.0,65,NaN,NaN,1
10027,10028,Female,South,Pro,E-Wallet,150.0,36,1.0,73.77,0
10028,10029,Female,East,Basic,Credit Card,150.0,124,2.0,72.01,1
10029,10030,Male,East,Basic,Credit Card,150.0,165,4.0,22.69,1
10030,10031,Female,East,Pro,Crypto,150.0,0,3.0,92.74,1

In [139]:
max_spend = df[df['Monthly_Spend'] > 290]
max_spend

,Customer_ID,Gender,Region,Subscription_Plan,Payment_Method,Age,Days_Since_Last_Login,Customer_Service_Calls,Monthly_Spend,Churn
100,10101,Male,West,Basic,PayPal,25.0,175,1.0,99999.99,1
101,10102,Female,North,Basic,Credit Card,16.0,60,1.0,99999.99,1
102,10103,Male,West,Basic,Crypto,24.0,137,1.0,99999.99,1
103,10104,Female,East,Pro,Credit Card,44.0,100,1.0,99999.99,0
104,10105,Unknown,North,Plus,Crypto,32.0,121,2.0,99999.99,1
105,10106,Male,East,Plus,Credit Card,34.0,59,2.0,99999.99,1
106,10107,Female,North,Basic,NaN,23.0,113,3.0,99999.99,1
107,10108,Female,West,Basic,E-Wallet,34.0,149,2.0,99999.99,1
108,10109,Male,West,Pro,Credit Card,23.0,74,4.0,99999.99,1
109,10110,Male,West,Basic,Credit Card,25.0,98,NaN,99999.99,1
110,10111,Male,South,Pro,Crypto,29.0,8,NaN,99999.99,0
10100,10101,Male,West,Basic,PayPal,25.0,175,1.0,99999.99,1
10101,10102,Female,North,Basic,Credit Card,16.0,60,1.0,99999.99,1
10102,10103,Male,West,Basic,Crypto,24.0,137,1.0,99999.99,1
10103,10104,Female,East,Pro,Credit Card,44.0,100,1.0,99999.99,0
10104,10105,Unknown,North,Plus,Crypto,32.0,121,2.0,99999.99,1
10105,10106,Male,East,Plus,Credit Card,34.0,59,2.0,99999.99,1
10106,10107,Female,North,Basic,NaN,23.0,113,3.0,99999.99,1
10107,10108,Female,West,Basic,E-Wallet,34.0,149,2.0,99999.99,1
10108,10109,Male,West,Pro,Credit Card,23.0,74,4.0,99999.99,1
10109,10110,Male,West,Basic,Credit Card,25.0,98,NaN,99999.99,1
10110,10111,Male,South,Pro,Crypto,29.0,8,NaN,99999.99,0

### String Datatypes

Use `set()` to view unique observations and to identify typographical errors

In [35]:
genders = set(df['Gender'])
regions = set(df['Region'])
subs = set(df['Subscription_Plan'])
payment = set(df['Payment_Method'])

print(genders)
print(regions)
print(subs)
print(payment)

{'Non-Binary', 'Male', 'Unknown', 'Female'}
{'South', 'East', 'West', 'east', 'North', 'north', 'south', 'west'}
{'Pro', 'Plus', 'PLUS', 'PRO', 'Basic', 'BASIC'}
{'PayPal', 'Crypto', 'E-Wallet', nan, 'Credit Card'}

**_Findings:_**
>---
**_Region_**<br>
    - Some values are not capitalized

**_Subscription Plan_**<br>
    - Some values are in uppercase
<hr>

**_Process_**
>---
Convert all to `Capitalized` format

In [100]:
for col in ['Region','Subscription_Plan']:
    df[col] = (
        df[col]
        .str.lower()
        .str.capitalize()
        .str.strip()
    )

In [101]:
genders = set(df['Gender'])
regions = set(df['Region'])
subs = set(df['Subscription_Plan'])
payment = set(df['Payment_Method'])

print(genders)
print(regions)
print(subs)
print(payment)

{'Non-Binary', 'Male', 'Unknown', 'Female'}
{'South', 'East', 'West', 'North'}
{'Basic', 'Pro', 'Plus'}
{'PayPal', 'Crypto', 'E-Wallet', nan, 'Credit Card'}